// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp-modified
// source: api/secrets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Variants of secret types
type SecretType int32

const (
	// default
	SecretType_UNKNOWN SecretType = 0
	// username, password, url, meta, etc.
	SecretType_CREDENTIALS SecretType = 1
	// password
	SecretType_PASSWORD SecretType = 2
	// number, date, name, csv
	SecretType_BANKCARD SecretType = 3
	// text (<=16 MB)
	SecretType_TEXT SecretType = 4
	// binary (+ text > 16 MB)
	SecretType_BINARY SecretType = 5
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREDENTIALS",
		2: "PASSWORD",
		3: "BANKCARD",
		4: "TEXT",
		5: "BINARY",
	}
	SecretType_value = map[string]int32{
		"UNKNOWN":     0,
		"CREDENTIALS": 1,
		"PASSWORD":    2,
		"BANKCARD":    3,
		"TEXT":        4,
		"BINARY":      5,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_secrets_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_api_secrets_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{0}
}

// ListSecretResponse is the response for the ListSecrets RPC.
type ListSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// secrets is a list of secrets meta.
	Secrets       []*Secret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"` // low data, dont send payload, metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretResponse) Reset() {
	*x = ListSecretResponse{}
	mi := &file_api_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretResponse) ProtoMessage() {}

func (x *ListSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretResponse.ProtoReflect.Descriptor instead.
func (*ListSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *ListSecretResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// CreateSecretRequest is the request for the CreateSecret RPC.
type CreateSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// secret is the secret to create.
	Secret        *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_api_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// CreateSecretChunkRequest is used to send chunks of a secret payload.
// 1 chunk: return Secret{payload = nil}, chunk = nil
// next chunks: return Secret = nil, chunk = payload
type CreateSecretChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta is the secret metadata.
	Meta *Secret `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// chunk is the chunk of the secret payload.
	Chunk         []byte `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretChunkRequest) Reset() {
	*x = CreateSecretChunkRequest{}
	mi := &file_api_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretChunkRequest) ProtoMessage() {}

func (x *CreateSecretChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretChunkRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretChunkRequest) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSecretChunkRequest) GetMeta() *Secret {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateSecretChunkRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// CreateSecretResponse is the response for the CreateSecret RPC.
type CreateSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the status of the response.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_api_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSecretResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetSecretRequest is the request for the GetSecret RPC.
type GetSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// secret_id is the ID of the secret to retrieve.
	SecretId      string `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_api_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

// GetSecretResponse is the response for the GetSecret RPC.
type GetSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// secret is the secret retrieved.
	Secret        *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_api_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// GetSecretChunkResponse return data as:
// 1 chunk: return Secret{payload = nil}, chunk = nil
// next chunks: return Secret = nil, chunk = payload
type GetSecretChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meta is the secret metadata.
	Meta *Secret `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// chunk is the chunk of the secret payload.
	Chunk         []byte `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretChunkResponse) Reset() {
	*x = GetSecretChunkResponse{}
	mi := &file_api_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretChunkResponse) ProtoMessage() {}

func (x *GetSecretChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretChunkResponse.ProtoReflect.Descriptor instead.
func (*GetSecretChunkResponse) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{6}
}

func (x *GetSecretChunkResponse) GetMeta() *Secret {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetSecretChunkResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// DeleteSecretRequest is the request for the DeleteSecret RPC.
type DeleteSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// secret_id is the ID of the secret to delete.
	SecretId      string `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_api_secrets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

// DeleteSecretResponse is the response for the DeleteSecret RPC.
type DeleteSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the status of the response.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_api_secrets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSecretResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Secret is the secret data.
type Secret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the secret.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type is the type of the secret.
	Type SecretType `protobuf:"varint,2,opt,name=type,proto3,enum=api.SecretType" json:"type,omitempty"` // чтобы десериализовать
	// title is the title of the secret.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// payload is the encrypted payload of the secret.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // зашифрованные данные
	// metadata is the metadata of the secret.
	Metadata string `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"` // произвольная мета
	// version is the version of the secret.
	Version int64 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"` // версионирование
	// created_at is the date and time the secret was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // дата создания
	// updated_at is the date and time the secret was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // дата обновления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_api_secrets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_api_secrets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_api_secrets_proto_rawDescGZIP(), []int{9}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_UNKNOWN
}

func (x *Secret) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Secret) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Secret) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Secret) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_secrets_proto protoreflect.FileDescriptor

const file_api_secrets_proto_rawDesc = "" +
	"\n" +
	"\x11api/secrets.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x12ListSecretResponse\x12%\n" +
	"\asecrets\x18\x01 \x03(\v2\v.api.SecretR\asecrets\":\n" +
	"\x13CreateSecretRequest\x12#\n" +
	"\x06secret\x18\x01 \x01(\v2\v.api.SecretR\x06secret\"Q\n" +
	"\x18CreateSecretChunkRequest\x12\x1f\n" +
	"\x04meta\x18\x01 \x01(\v2\v.api.SecretR\x04meta\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\".\n" +
	"\x14CreateSecretResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"/\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"8\n" +
	"\x11GetSecretResponse\x12#\n" +
	"\x06secret\x18\x01 \x01(\v2\v.api.SecretR\x06secret\"O\n" +
	"\x16GetSecretChunkResponse\x12\x1f\n" +
	"\x04meta\x18\x01 \x01(\v2\v.api.SecretR\x04meta\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\"2\n" +
	"\x13DeleteSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\".\n" +
	"\x14DeleteSecretResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x99\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.api.SecretTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\\\n" +
	"\n" +
	"SecretType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vCREDENTIALS\x10\x01\x12\f\n" +
	"\bPASSWORD\x10\x02\x12\f\n" +
	"\bBANKCARD\x10\x03\x12\b\n" +
	"\x04TEXT\x10\x04\x12\n" +
	"\n" +
	"\x06BINARY\x10\x052\xb1\x03\n" +
	"\x0eSecretsService\x12>\n" +
	"\vListSecrets\x12\x16.google.protobuf.Empty\x1a\x17.api.ListSecretResponse\x12C\n" +
	"\fCreateSecret\x12\x18.api.CreateSecretRequest\x1a\x19.api.CreateSecretResponse\x12P\n" +
	"\x12CreateSecretStream\x12\x1d.api.CreateSecretChunkRequest\x1a\x19.api.CreateSecretResponse(\x01\x12:\n" +
	"\tGetSecret\x12\x15.api.GetSecretRequest\x1a\x16.api.GetSecretResponse\x12G\n" +
	"\x0fGetSecretStream\x12\x15.api.GetSecretRequest\x1a\x1b.api.GetSecretChunkResponse0\x01\x12C\n" +
	"\fDeleteSecret\x12\x18.api.DeleteSecretRequest\x1a\x19.api.DeleteSecretResponseB+Z)github.com/anon-d/gophKeeper/pkg/proto;pbb\x06proto3"

var (
	file_api_secrets_proto_rawDescOnce sync.Once
	file_api_secrets_proto_rawDescData []byte
)

func file_api_secrets_proto_rawDescGZIP() []byte {
	file_api_secrets_proto_rawDescOnce.Do(func() {
		file_api_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_secrets_proto_rawDesc), len(file_api_secrets_proto_rawDesc)))
	})
	return file_api_secrets_proto_rawDescData
}

var file_api_secrets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_secrets_proto_goTypes = []any{
	(SecretType)(0),                  // 0: api.SecretType
	(*ListSecretResponse)(nil),       // 1: api.ListSecretResponse
	(*CreateSecretRequest)(nil),      // 2: api.CreateSecretRequest
	(*CreateSecretChunkRequest)(nil), // 3: api.CreateSecretChunkRequest
	(*CreateSecretResponse)(nil),     // 4: api.CreateSecretResponse
	(*GetSecretRequest)(nil),         // 5: api.GetSecretRequest
	(*GetSecretResponse)(nil),        // 6: api.GetSecretResponse
	(*GetSecretChunkResponse)(nil),   // 7: api.GetSecretChunkResponse
	(*DeleteSecretRequest)(nil),      // 8: api.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),     // 9: api.DeleteSecretResponse
	(*Secret)(nil),                   // 10: api.Secret
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_api_secrets_proto_depIdxs = []int32{
	10, // 0: api.ListSecretResponse.secrets:type_name -> api.Secret
	10, // 1: api.CreateSecretRequest.secret:type_name -> api.Secret
	10, // 2: api.CreateSecretChunkRequest.meta:type_name -> api.Secret
	10, // 3: api.GetSecretResponse.secret:type_name -> api.Secret
	10, // 4: api.GetSecretChunkResponse.meta:type_name -> api.Secret
	0,  // 5: api.Secret.type:type_name -> api.SecretType
	11, // 6: api.Secret.created_at:type_name -> google.protobuf.Timestamp
	11, // 7: api.Secret.updated_at:type_name -> google.protobuf.Timestamp
	12, // 8: api.SecretsService.ListSecrets:input_type -> google.protobuf.Empty
	2,  // 9: api.SecretsService.CreateSecret:input_type -> api.CreateSecretRequest
	3,  // 10: api.SecretsService.CreateSecretStream:input_type -> api.CreateSecretChunkRequest
	5,  // 11: api.SecretsService.GetSecret:input_type -> api.GetSecretRequest
	5,  // 12: api.SecretsService.GetSecretStream:input_type -> api.GetSecretRequest
	8,  // 13: api.SecretsService.DeleteSecret:input_type -> api.DeleteSecretRequest
	1,  // 14: api.SecretsService.ListSecrets:output_type -> api.ListSecretResponse
	4,  // 15: api.SecretsService.CreateSecret:output_type -> api.CreateSecretResponse
	4,  // 16: api.SecretsService.CreateSecretStream:output_type -> api.CreateSecretResponse
	6,  // 17: api.SecretsService.GetSecret:output_type -> api.GetSecretResponse
	7,  // 18: api.SecretsService.GetSecretStream:output_type -> api.GetSecretChunkResponse
	9,  // 19: api.SecretsService.DeleteSecret:output_type -> api.DeleteSecretResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_secrets_proto_init() }
func file_api_secrets_proto_init() {
	if File_api_secrets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_secrets_proto_rawDesc), len(file_api_secrets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_secrets_proto_goTypes,
		DependencyIndexes: file_api_secrets_proto_depIdxs,
		EnumInfos:         file_api_secrets_proto_enumTypes,
		MessageInfos:      file_api_secrets_proto_msgTypes,
	}.Build()
	File_api_secrets_proto = out.File
	file_api_secrets_proto_goTypes = nil
	file_api_secrets_proto_depIdxs = nil
}
