// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp-modified
// source: api/secrets.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsService_ListSecrets_FullMethodName        = "/api.SecretsService/ListSecrets"
	SecretsService_CreateSecret_FullMethodName       = "/api.SecretsService/CreateSecret"
	SecretsService_CreateSecretStream_FullMethodName = "/api.SecretsService/CreateSecretStream"
	SecretsService_GetSecret_FullMethodName          = "/api.SecretsService/GetSecret"
	SecretsService_GetSecretStream_FullMethodName    = "/api.SecretsService/GetSecretStream"
	SecretsService_UpdateSecret_FullMethodName       = "/api.SecretsService/UpdateSecret"
	SecretsService_DeleteSecret_FullMethodName       = "/api.SecretsService/DeleteSecret"
)

// SecretsServiceClient is the client API for SecretsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretsService provides services for managing secrets.
type SecretsServiceClient interface {
	// ListSecrets returns a list of all secrets meta.
	ListSecrets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSecretResponse, error)
	// CreateSecret creates a new secret.
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error)
	// CreateSecretStream creates a new secret using a stream of chunks.
	CreateSecretStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateSecretChunkRequest, CreateSecretResponse], error)
	// GetSecret returns a secret by its ID.
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	// GetSecretStream returns a stream of chunks for a secret by its ID.
	GetSecretStream(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSecretChunkResponse], error)
	// UpdateSecret updates a secret with optimistic locking.
	UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error)
	// DeleteSecret deletes a secret by its ID.
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
}

type secretsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsServiceClient(cc grpc.ClientConnInterface) SecretsServiceClient {
	return &secretsServiceClient{cc}
}

func (c *secretsServiceClient) ListSecrets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) CreateSecretStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateSecretChunkRequest, CreateSecretResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecretsService_ServiceDesc.Streams[0], SecretsService_CreateSecretStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateSecretChunkRequest, CreateSecretResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecretsService_CreateSecretStreamClient = grpc.ClientStreamingClient[CreateSecretChunkRequest, CreateSecretResponse]

func (c *secretsServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) GetSecretStream(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSecretChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecretsService_ServiceDesc.Streams[1], SecretsService_GetSecretStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSecretRequest, GetSecretChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecretsService_GetSecretStreamClient = grpc.ServerStreamingClient[GetSecretChunkResponse]

func (c *secretsServiceClient) UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_UpdateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsServiceServer is the server API for SecretsService service.
// All implementations should embed UnimplementedSecretsServiceServer
// for forward compatibility.
//
// SecretsService provides services for managing secrets.
type SecretsServiceServer interface {
	// ListSecrets returns a list of all secrets meta.
	ListSecrets(context.Context, *emptypb.Empty) (*ListSecretResponse, error)
	// CreateSecret creates a new secret.
	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error)
	// CreateSecretStream creates a new secret using a stream of chunks.
	CreateSecretStream(grpc.ClientStreamingServer[CreateSecretChunkRequest, CreateSecretResponse]) error
	// GetSecret returns a secret by its ID.
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	// GetSecretStream returns a stream of chunks for a secret by its ID.
	GetSecretStream(*GetSecretRequest, grpc.ServerStreamingServer[GetSecretChunkResponse]) error
	// UpdateSecret updates a secret with optimistic locking.
	UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error)
	// DeleteSecret deletes a secret by its ID.
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
}

// UnimplementedSecretsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsServiceServer struct{}

func (UnimplementedSecretsServiceServer) ListSecrets(context.Context, *emptypb.Empty) (*ListSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedSecretsServiceServer) CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedSecretsServiceServer) CreateSecretStream(grpc.ClientStreamingServer[CreateSecretChunkRequest, CreateSecretResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateSecretStream not implemented")
}
func (UnimplementedSecretsServiceServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedSecretsServiceServer) GetSecretStream(*GetSecretRequest, grpc.ServerStreamingServer[GetSecretChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSecretStream not implemented")
}
func (UnimplementedSecretsServiceServer) UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecret not implemented")
}
func (UnimplementedSecretsServiceServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedSecretsServiceServer) testEmbeddedByValue() {}

// UnsafeSecretsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsServiceServer will
// result in compilation errors.
type UnsafeSecretsServiceServer interface {
	mustEmbedUnimplementedSecretsServiceServer()
}

func RegisterSecretsServiceServer(s grpc.ServiceRegistrar, srv SecretsServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsService_ServiceDesc, srv)
}

func _SecretsService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ListSecrets(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_CreateSecretStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SecretsServiceServer).CreateSecretStream(&grpc.GenericServerStream[CreateSecretChunkRequest, CreateSecretResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecretsService_CreateSecretStreamServer = grpc.ClientStreamingServer[CreateSecretChunkRequest, CreateSecretResponse]

func _SecretsService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_GetSecretStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSecretRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecretsServiceServer).GetSecretStream(m, &grpc.GenericServerStream[GetSecretRequest, GetSecretChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecretsService_GetSecretStreamServer = grpc.ServerStreamingServer[GetSecretChunkResponse]

func _SecretsService_UpdateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).UpdateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_UpdateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).UpdateSecret(ctx, req.(*UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsService_ServiceDesc is the grpc.ServiceDesc for SecretsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SecretsService",
	HandlerType: (*SecretsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSecrets",
			Handler:    _SecretsService_ListSecrets_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _SecretsService_CreateSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _SecretsService_GetSecret_Handler,
		},
		{
			MethodName: "UpdateSecret",
			Handler:    _SecretsService_UpdateSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _SecretsService_DeleteSecret_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateSecretStream",
			Handler:       _SecretsService_CreateSecretStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSecretStream",
			Handler:       _SecretsService_GetSecretStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/secrets.proto",
}
